name: "check-secrets"
description: "Mini action for verifying that certain secrets have been passed to the job"
inputs:
  names:
    description: |
      A list of secrets which must be available/non-empty for the job to succeed
      You should pass them like this:

          with:
              names: |
                SECRET_NAME_1
                SECRET_NAME_2

    required: true
runs:
  using: "node20"
  main: "dist/index.js"
